branches: ['master']
ci: true
debug: true
dryRun: false
tagFormat: '${version}'

# Global plugin options (will be passed to all plugins)
preset: 'conventionalcommits'
gitlabUrl: 'http://gitlab.int.gofura.com/'
slackWebhook: 'https://mattermost.gofura.com/hooks/q3dtkec6yjyg9x6616o3atgkkr'

# Responsible for verifying conditions necessary to proceed with the release:
# configuration is correct, authentication token are valid, etc...
verifyConditions:
  - '@semantic-release/changelog'
  - '@semantic-release/git'
  - '@semantic-release/gitlab'
  - 'semantic-release-slack-bot'

# Responsible for determining the type of the next release (major, minor or patch).
# If multiple plugins with a analyzeCommits step are defined, the release type will be
# the highest one among plugins output.
# Look details at: https://github.com/semantic-release/commit-analyzer#configuration
analyzeCommits:
  - path: '@semantic-release/commit-analyzer'

# Responsible for generating the content of the release note.
# If multiple plugins with a generateNotes step are defined,
# the release notes will be the result of the concatenation of each plugin output.
generateNotes:
  - path: '@semantic-release/release-notes-generator'
    writerOpts:
      groupBy: 'type'
      commitGroupsSort: 'title'
      commitsSort: 'header'
    # linkCompare: true
    # linkReferences: true
    # parserOpts:
    #   # detect JIRA issues in merge commits
    #   issuePrefixes: ['FB-', 'DEV-', 'ADM-', 'ERP-', 'HB-', 'LB-', 'MOB-', 'TR-', 'SADM-', 'SERP-', 'SHB-', 'SLOAD-', 'SM-', 'ST-']
    #   mergePattern: "^Merge branch '(.*)' into (.*)$"
    #   mergeCorrespondence: ['branch_src', 'branch_dst']

# Responsible for preparing the release, for example creating or updating files
# such as package.json, CHANGELOG.md, documentation or compiled assets
# and pushing a commit.
prepare:
  - path: '@semantic-release/exec'
    cmd: './deployment/version-plaintext-set.sh ${nextRelease.version}'
  - path: '@semantic-release/changelog'
  - path: '@semantic-release/git'
    message: 'RELEASE: ${nextRelease.version}'
    assets: ['CHANGELOG.md', 'version']

# Responsible for publishing the release.
publish:
  - path: '@semantic-release/gitlab'

success:
  - path: 'semantic-release-slack-bot'
    notifyOnSuccess: true
    markdownReleaseNotes: false
    onSuccessTemplate:
      channel: 'alerts_backend_release'
      attachments:
        - color: '#00c100'
          title: '$package_name'
          title_link: '$repo_url'
          text: '$release_notes'
          footer: 'version: $npm_package_version'

fail:
  - path: 'semantic-release-slack-bot'
    notifyOnFail: true
